#!/usr/bin/env bash
# commands to install ngnix on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Ngnix HTTP"

echo "Hello world!" | sudo tee /var/www/html/index.html

#rtesting nginx configuration 
sudo nginx -t 

sudo service ngnix reload
